### PR TITLE
call event handlers when value property changes

### PR DESCRIPTION
**Pull request by celanajaya**
made two changes:
1. event handlers called whenever value property changes

2. value property updated on textdidendediting

### CODE REVIEW

**Comment by massimobio** [comment]
I'm wondering is firing the delegate and completion closure in the didSet of value is the right approach.
The delegate methods are now called when the value is set programmatically. Is that an expected behavior? Is the delegate method of NSTextFiled for example called when we set the value programmatically?

**Comment by celanajaya** [comment]
My understanding of the purpose of that delegate/closure method is to update any external classes when the value changes. The way we've named them seems to imply that as well. So seemed to make the most sense to move the calls there. 

Are there down sides to this approach that I'm not considering?

I don't think we need to consider the NSTextField delegate methods in this case, because we're really just interested in the change to the "value" property. How that value changes (via user interaction, or in code), doesn't matter, I don't think. But again, if there's a case I'm not considering, let me know.

**Comment by massimobio** [comment]
I was giving the NsTextField delegate as an example of a UI component and how it works. 
I believe we need to make a distinction between user generated value changes and code generated value changes. 
I think that's how AppKit and UIKit work. If you set for example the value in a slider programmatically, the delagate method is not called but of the user drags the slider then the delegate is called. 
This is important if you think of model vs view. 
If the view changes (user input) we want our delegate methods to update the model. 
If the model changes (maybe new data was done loaded) we want update the UI but now we don't want the UI to fire it's delegate and try to update the model because then we'd be in an infinite loop.

**Comment by celanajaya** [comment]
thinking more about this, I think I'm seeing your point....this brings up whether we should be extending/forwarding more the NSTextFieldDelegate to the developer. Should we have our own versions of didEndEditing, shouldChangeText, shouldSelectText, etc...?

Are our valueChanged methods really about the value property only?
or are they also about interactions with the textField?
how separate should they be? 

I guess I'm leaning towards total separation, by having onValueChanged be connected only to the change on the value property. But I also can see why we'd want to think of it as tied to TextField interactions.

Crazy how something this small can lead major philosophical considerations!

**Comment by celanajaya** [comment]
I see your point. Depending, on whether the model's configured to automatically update the UI when it's value changes, even if it doesn't create a loop, it is still inefficient, because the view would be trying to update the model to the value it already has.

understood, we should go back to the original way!

**Comment by massimobio** [comment]
yeah, maybe one method called something like userDidChangeValue() which calls the delegate methods and the closure? It will need to be called from when a click and drag happens, when a text edit ends and in the future when a stepper action happens.

I'm not sure about your other point about the other text view delegate methods. Since we are a subclass of NSTextView, all those delegate methods are all there and the user of our component can conform to that delegate if she wants.

**Comment by celanajaya** [comment]
ah yes...I see. Our component is only overriding NSTextViewDelegate and NSText Delegate methods, while our NSTextfieldDelegate remains unset. 

I like the idea of combining our delegate/closure calls into a single method.

**Comment by massimobio** [comment]
Looking good. I just made the new userDidChangeValue method private.

**Pull request merged**
